# Generated by Django 5.1.2 on 2024-10-18 12:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('fecha_lanzamiento', models.DateField()),
                ('portada', models.ImageField(blank=True, upload_to='album_portadas/')),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=100, unique=True)),
                ('bio', models.TextField(blank=True)),
                ('ciudad', models.CharField(blank=True, max_length=150)),
                ('foto_perfil', models.ImageField(blank=True, upload_to='fotos_perfil/')),
                ('fecha_nac', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('artista', models.CharField(max_length=100)),
                ('duracion', models.DurationField()),
                ('archivo_audio', models.FileField(upload_to='canciones/')),
                ('portada', models.ImageField(blank=True, upload_to='cancion_portadas/')),
                ('fecha_subida', models.DateTimeField(default=django.utils.timezone.now)),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='canciones', to='socialSound.album')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialSound.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('cancion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialSound.cancion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialSound.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('rock', 'Rock'), ('jazz', 'Jazz'), ('metal', 'Metal'), ('electronica', 'Electrónica'), ('pop', 'Pop'), ('hiphop', 'Hip-Hop'), ('reggae', 'Reggae'), ('blues', 'Blues'), ('classical', 'Clásica'), ('country', 'Country'), ('dance', 'Dance'), ('disco', 'Disco'), ('dubstep', 'Dubstep'), ('edm', 'EDM (Electronic Dance Music)'), ('funk', 'Funk'), ('gospel', 'Gospel'), ('grunge', 'Grunge'), ('hardrock', 'Hard Rock'), ('indie', 'Indie'), ('latin', 'Latina'), ('lofi', 'Lo-Fi'), ('opera', 'Ópera'), ('punk', 'Punk'), ('rnb', 'R&B (Rhythm and Blues)'), ('rap', 'Rap'), ('salsa', 'Salsa'), ('soul', 'Soul'), ('techno', 'Techno'), ('trance', 'Trance'), ('trap', 'Trap'), ('house', 'House'), ('ambient', 'Ambient'), ('acoustic', 'Acústica'), ('alternative', 'Alternativa'), ('chillout', 'Chillout'), ('drumandbass', 'Drum and Bass'), ('electro', 'Electro'), ('experimental', 'Experimental'), ('folk', 'Folk'), ('hardcore', 'Hardcore'), ('idm', 'IDM (Intelligent Dance Music)'), ('industrial', 'Industrial'), ('kpop', 'K-Pop'), ('metalcore', 'Metalcore'), ('newage', 'New Age'), ('noise', 'Noise'), ('progressiverock', 'Progressive Rock'), ('psytrance', 'Psytrance'), ('reggaeton', 'Reggaetón'), ('synthwave', 'Synthwave'), ('vaporwave', 'Vaporwave'), ('world', 'World Music'), ('ska', 'Ska'), ('tango', 'Tango'), ('grindcore', 'Grindcore'), ('postrock', 'Post-Rock'), ('drill', 'Drill'), ('shoegaze', 'Shoegaze'), ('glitch', 'Glitch'), ('breakbeat', 'Breakbeat'), ('emo', 'Emo'), ('christian', 'Cristiana'), ('jpop', 'J-Pop'), ('jrock', 'J-Rock'), ('futurebass', 'Future Bass'), ('progressivehouse', 'Progressive House'), ('moombahton', 'Moombahton'), ('dancehall', 'Dancehall'), ('dub', 'Dub')], max_length=50)),
                ('canciones', models.ManyToManyField(related_name='etiquetas', to='socialSound.cancion')),
            ],
        ),
        migrations.CreateModel(
            name='Seguidores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('seguido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguido', to='socialSound.usuario')),
                ('seguidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguidor', to='socialSound.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_reporte', models.CharField(choices=[('spam', 'Spam'), ('contenido_inapropiado', 'Contenido Inapropiado'), ('derechos_autor', 'Infracción de Derechos de Autor'), ('otro', 'Otro')], max_length=50)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_reporte', models.DateTimeField(default=django.utils.timezone.now)),
                ('resuelto', models.BooleanField(default=False)),
                ('cancion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes', to='socialSound.cancion')),
                ('comentario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes', to='socialSound.comentario')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to='socialSound.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(max_length=255)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('publica', models.BooleanField(default=True)),
                ('canciones', models.ManyToManyField(related_name='playlists', to='socialSound.cancion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialSound.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='MensajePrivado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_read', models.BooleanField(default=False)),
                ('emisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emisor', to='socialSound.usuario')),
                ('receptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receptor', to='socialSound.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_like', models.DateTimeField(default=django.utils.timezone.now)),
                ('activo', models.BooleanField(default=True)),
                ('cancion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialSound.cancion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialSound.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('miembros', models.ManyToManyField(related_name='grupos', to='socialSound.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='artista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialSound.usuario'),
        ),
        migrations.CreateModel(
            name='Guardado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_guardado', models.DateTimeField(default=django.utils.timezone.now)),
                ('cancion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialSound.cancion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialSound.usuario')),
            ],
            options={
                'unique_together': {('usuario', 'cancion')},
            },
        ),
    ]
